server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: India#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL8Dialect
  
  application:
    name: USER-SERVICE    
    
  config:
    import: optional:configserver:http://localhost:8085
    
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-69692373.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oactn1cyfxlhNbYl5d7
            client-secret: 1H8RHeGhRNaP83UyrDxiMuOMMgcnQzS_MI4hPhCTSfp1VfvOFPcd9FlCvtjMal7i
         
        provider:
          okta:
            issuer-uri: https://dev-69692373.okta.com/oauth2/default
                
            
    
management:
  endpoints:
    web:
      exposure:
        include: 
        - health
        
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true
      
 
resilience4j:
  circuitbreaker:
    instances:
      user-rating-hotel-CB:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
  retry:
    instances:
      user-rating-hotel-RETRY:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      user-rating-hotel-rate:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
 
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:1001/eureka


okta:
  oauth2:
    issuer: https://dev-69692373.okta.com/oauth2/default
    audience: api://default


